### ISSUE TITLE
Allow static methods to be called and inherited the same way variables are

### ISSUE THREAD

**Issue by Sharsie** [soberwp/controller#59] opened 2017-12-22 08:06 UTC
**The problem:**
At the moment we can use public methods in the controllers which are then translated into variables to be used in blade templates.

These variables can be inherited from parent controllers using the `Tree` interface, or inherited from the `App` controller

Static methods, however, are always tied to the Controller class and cannot be inherited, so they always need to be called from the templates referencing the Controller itself

In an example: we cannot use methods from specific controllers in templates which are shared between multiple contexts
lets say an `entry-meta.blade.php` which is loaded in Singular context and Home context always has to use `App::method()` and never `Home::method()` or `Singular::method()`

**The use case:**
Imagine an entry-meta.blade.php which prints article categories

```
<div class="entry-meta">
    @foreach(App::categories() as $cat)
      {{ $cat }}
    @endforeach
</div>
```

Then for our use case, we want to print only a single category on the homepage, but list all categories in the article detail, so effectively we want to slice the array of categories for Singular context
At this moment we have two ways to achieve this:

1. Use two template partials: `entry-meta.blade.php` and `entry-meta-singular.blade.php` - One would call `App::categories()` while the later would call `Singular::categories()` - this effectively duplicates our template partials
2. Create this logic inside the `App::categories()` where we would add exceptions when `is_singular()` is true - which sort of goes against the controller design in itself, especially when the logic becomes more specific (Home context, Category context, page context, post context)

**Proposed solution:**
Have the static methods added to blade compiler as directives.
This, however, should be noted in the readme as well, because someone could define a static method `foreach` or something else from the default blade directives effectively overriding its function

Possibly a list of default blade directives should be checked against the method names and an exception should be thrown in that case

There is one more problem with the directives and that is the blade template cache.
So if I were to implement a method on the App class, call it from a template, it will get cached and the method would always be called from the App class until something in the template is changed. Even if I then define the same method on a more specific controller. There could be a solution using some sort of Middleware which would be called from the cached template and would then call the registeted method, however I am not sure if this is not an overkill for what I am trying to accomplish. Any thoughts on this?

I will submit a PR in a bit with the proposed solution, so lets have a look if we can think of something better? :)

**Comment by slackday** [comment] 2017-12-22 10:55
When I want to re-use static functions I usually create a trait in `app/controllers/partials`

```
namespace App;

trait Categories
{
  public static function getCategories()
  {
      ...
  }
}
```

Then in single controller or whatever 

```
namespace App;

use Sober\Controller\Controller;

class SingleCategory extends Controller
{
  use Categories;
}
```

And calling it in template

`SingleCategory::getCategories()`

Did you try this for reusability?

**Comment by Sharsie** [comment] 2017-12-22 11:33
Indeed I did, the issue is when calling it from common templates (like partials/entry-meta) which are shared accross different contexts (homepage, category page, single). You cannot(well, should not) actually reference `SingleCategory` controller because the template file will be also called from a post (or homepage) where `SingleCategory` might not be relevant.
Then you would need to create a different template for entry-meta specific to SinglePost and call `SinglePost::getCategories()` which leads to unnecessary duplication of templates.

Hence the proposed solution, where we could have a single point of entry (i.e. `@getCategories`) and the controller hierarchy would decide which method to execute (whether `SingleCategory::getCategories()` or `SinglePost::getCategories()` and so on)
I actually have a working solution locally, just strugling a bit with the tree inheritance

**Comment by Sharsie** [comment] 2017-12-27 10:28
After fiddling around with it for a while, I do not think this solution is a good way to go.

The reason being - it is impossible to call the directives in for loops, i.e. now we can do something like

```
@foreach (App::getCategories() as $category)
@endforeach

OR

@foreach (SingleCategory::getCategories() as $category)
@endforeach
```
using the directives, it is impossible to call
```
@foreach (@getCategories as $category)
@endforeach
```

**Comment by Sharsie** [comment] 2018-01-08 05:57
@darrenjacoby 

Darren can I ask for your take on this topic? Would this be something you would consider worthwhile implementing?

The more I want to customize certain parts of the theme, the more I am hitting on this wall, where I am forced to create duplicate templates, so I would like to know if this is the way it is going to be or whether it would be worth my time to think of a solution.

**Comment by darrenjacoby** [comment] 2018-01-08 07:08
@sharsie will take a look

**Comment by darrenjacoby** [comment] 2018-01-08 15:00
@Sharsie 

I'm still putting some thought into perhaps a better way to handle this, letting the WordPress hierarchy determine the Class alias to use is an interesting approach that could work.

How it works at the moment is that all static methods are accessible regardless of template.  The `class_alias` is just  removing the namespace and referencing the class. For example App::function(). This removes the chance of conflicts as each class name is unique.

Using this logic, you could create `EntryMeta.php` under Controllers

```php
<?php

namespace App\Controllers;

use Sober\Controller\Controller;

class EntryMeta extends Controller
{
    public static function getTerms()
    {
        return 'terms data';
    }
}
```

Then, regardless of template, you could use {{ EntryMeta::getTerms() }}

The upside of this, is that just from viewing the template, it's easy to determine the origin/class of the method. However, following the same approach with data, it could be nice to have a shorthand that is available for only that view (ie. same approach as data) and using Run::getTerms() or something.  The problem is that two classes could have the same function getTerms(), do I then override the same way as data is handled? 

Thoughts?

**Comment by Sharsie** [comment] 2018-01-30 03:44
Sorry for the silence, it's been crazy busy and I don't think I'll have to time to think on this until the second week of february.
Okay, I understand the logic behind this, as far as I see it, you will always be able to call static methods of whatever class there is, so this behaviour would never change. From my perspective, this is just a method call, just as if I would be calling `get_the_title()` or anything else right inside the template.

```
The problem is that two classes could have the same function getTerms(), do I then override the same way as data is handled?
```
This was my previous thought, handle the methods in the same way the data is handled and provide it through a common method caller. The original functionality would be untouched.

Initially I fiddled with the concept of storing the method calls inside variables prefixed with _call, as in `_call_get_terms()`. But I didn't like the concept very much. 
I was also thinking that it would be possible to snake_case the public methods and camelCase the public static methods. But then there would be conficts between the two (single name) so this did not quite work as well and would still need the prefix.
My last idea was to provide, as you have hinted, a common caller such as "Run::getTerms()" or "View::getTerms()" or similiar. I think I like this one the most also because we could catch invalid method calls with `__call`

**Comment by darrenjacoby** [comment] 2018-02-04 09:01
Yeah, I'll look into implementing an interface for the current view (like View::).

It'll just be an extra alias for methods that fall within the scope of the current template, so it's just some syntax sugar really.

Closing for now, but will take a look at this in the future.

**Closed by darrenjacoby** 2018-02-04 09:01 UTC
